### PR TITLE
Added some Info to README.md

### PR DESCRIPTION
**Pull request by Jaya2812**
I'm a newbie...please give this chance to me.

### CODE REVIEW

**Comment by bhavesh1129** [comment]
Kindly resolve the conflicts.

**Comment by bhavesh1129** [comment]
Kindly resolve the conflicts!

**Comment by Jaya2812** [comment]
will it work now...if it do, please let me know(i want to learn things)

**Comment by bhavesh1129** [comment]
> will it work now...if it do, please let me know(i want to learn things)

Yeah, its absolutely fine good work @Jaya2812!

**Pull request merged**
